### ISSUE TITLE
Incompatible with prettier

### ISSUE THREAD

**Issue by robMolloy** [Huegelkoenig/line-logger-VSCE#1]
I know this is not necessarily a problem with line logger, apologies.

Prettier (and other formatters) put a space between a multiline comments and text/number.

When line logger is called again it will put the line number in between the last entry;

i.e.
/*LL*/1047

becomes...

/*LL*/1047 1047

**Comment by robMolloy** [comment]
Thanks for any help you can provide

**Comment by Huegelkoenig** [comment]
As a hotfix I've added some new commands (log space left, log space right, delete space left, delete space right) to deal with this issue. See the adjusted Readme.md for details.
Note, that these new commands only work with a single space between the tokens and the line numbers, atm.
Please let me know, if this resolved your problem.

**Comment by robMolloy** [comment]
That works perfectly for me! Thanks for sorting so quickly, I really appreciate it.

I hope this isn't being too cheeky...
I know it's easy to quickly type /*LL*/ but have you considered adding a shortcut which inserts the token?

Great extension with or without it, thanks!

**Comment by Huegelkoenig** [comment]
Sorry for the late response.
Actually, i haven't even thought about that and i think that's a great idea. But since there are so many extensions out there, i'm pretty sure a fixed shortcut would only lead to conflicts with other extension. So i'm not going to do this.

But you can assign your own shortcut for this task.
Simply go to  File -> Preferences -> Keyboard Shortcuts.
On the top right corner there should be a symbol stating "Open Keyboard Shortcuts (JSON)".  This should open the "keybindings.json" file.
Alternatively you can open this file by using the command console: Hit "control+shift+p" and enter "Open Keyboard Shortcut (JSON)" in the console.
Alternatively you can open this file manually. In Win10 it should be stored under "C:\users\USERNAME\AppData\Roaming\code\User".

Now you can add your own Snippet. The following example inserts the line-logger token   /\*LL\*/   by pressing control+alt+enter
```
[
    {
        "key": "ctrl+alt+enter",
        "command": "editor.action.insertSnippet",
        "when": "editorTextFocus,
        "args": {
            "snippet": "/*LL*/"
        }
    }
]
```


Since line-logger tokens depend on the underlying programming language, you can also specify the language.
By pressing ctrl+L the following snippets insert the line-logger token   /\*LL\*/   only for javascript- and C++-files and the line-logger token <#LL#>  for powershell-files.

```
[
    {
        "key": "ctrl+L",
        "command": "editor.action.insertSnippet",
        "when": "editorTextFocus && editorLangId =~ /javascript|cpp/",
        "args": {
            "snippet": "/*LL*/"
        }
    },
    {
        "key": "ctrl+L",
        "command": "editor.action.insertSnippet",
        "when": "editorTextFocus && editorLangId == 'powershell'",
        "args": {
            "snippet": "<#LL#>"
        }
    }
]
```

Hope this helps.
